### ISSUE TITLE
Error creating object for class Tablelnfo. 

### ISSUE THREAD

**Issue by Justintime22** [fulcrumapp/tableau-webdataconnector#1]
Below is the error message I have been receiving since your update:

**The web data connector returned invalid data.
Error creating object for class Tablelnfo. The input data for one of the contained objects is invalid. The input Id ‘marker-color’ is invalid. The Id must contain only letters, numbers or underscores.**

Trying to refresh my data connection with the connector results in a neverending updating data dialogue box.

![image](https://user-images.githubusercontent.com/53228197/61724062-0b349700-ad22-11e9-8ef4-7bf9794bd4f6.png)

**Comment by bmcbride** [comment]
Thanks for the update @Justintime22 ! I believe I have addressed this issue. Please refresh and try again. Feel free to reopen this issue if necessary.
